version: '3.8'

services:
  pgvector-perf-postgres:
    image: pgvector/pgvector:pg14
    container_name: pgvector-perf-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgvector-perf-password
      POSTGRES_DB: pgvector-perf
    ports:
      - "15432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '1.0'

  pgvector-perf-pgweb:
    image: sosedoff/pgweb
    container_name: pgvector-perf-pgweb
    ports:
      - "15433:8081"
    links:
      - pgvector-perf-postgres:pgvector-perf-postgres
    environment:
      - DATABASE_URL=postgres://postgres:pgvector-perf-password@pgvector-perf-postgres:5432/postgres?sslmode=disable
    depends_on:
      - pgvector-perf-postgres
    restart: always
